# This file is part of cernopendata-client.
#
# Copyright (C) 2020, 2022 CERN.
#
# cernopendata-client is free software; you can redistribute it and/or modify
# it under the terms of the GPLv3 license; see LICENSE file for more details.

[tox]
envlist = py27, py36, py37, py38, py39, py310

[testenv]
deps = pytest
       pytest-cov
commands = {envpython} setup.py test
